from docx import Document
from pathlib import Path
import uuid

def generate_docx(content: str, title: str = "AI Output", filename: str = "DOC-GEN") -> str:
    """
    Generate a .docx document with a given content and title.
    Returns the saved file path.
    """
    doc = Document()
    doc.add_heading(title, level=1)
    doc.add_paragraph(content)

    file_id = filename or f"{title.replace(' ', '_')}_{uuid.uuid4().hex[:8]}.docx"
    output_path = Path("generated") / file_id
    output_path.parent.mkdir(exist_ok=True)
    doc.save(str(output_path))

    return str(output_path)

# Optional CLI usage
if __name__ == "__main__":
    path = generate_docx("This is a test document generated by the AI Studio.", "Sample Title")
    print(f"Document saved at: {path}")
